# new_wheel_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  # Position Controllers --------------------------------------
  back_fork_effort_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute_7
    pid: {p: 2.0, i: 0.01, d: 1.0}
  # Revolute 17_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: Revolute_17
  #   pid: {p: 1.0, i: 0.01, d: 1.0}
  # Revolute 20_position_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: Revolute_20
  #   pid: {p: 1.0, i: 0.01, d: 1.0}
  back_wh_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: Revolute_25
    pid: {p: 1.0, i: 1.0, d: 1.0}
