# motor_0419_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 200

  # Position Controllers --------------------------------------
  # front_fork_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: front_fork
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
  # front_wh_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: front_wh
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
  back_fork_position_controller:
    type: effort_controllers/JointPositionController
    joint: back_fork
    pid: {p: 5.0, i: 0.01, d: 5.0}
  # back_wh_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: back_wh
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
